# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Personal Portfolio
email: kaloyanpetev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal Portfolio website. Using Jekyll as static site generator, Sass, Gulp, Github Pages.
destination: docs
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kicata
github_username:  KaloyanTodorov

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docs
  - _assets
  - gulpfile.js
  - package.json
  - package-lock.json

navigation:
  - url: 
    title: Home
  - url: about/
    title: About
  - url: work/
    title: Work
  - url: education/
    title: Education
  - url: fun/
    title: Fun
  - url: contacts/
    title: Contacts

sociallinks:
  - title: linkedin
    url: https://www.linkedin.com/in/kaloyan-todorov-aa723952/
    icon: fab fa-linkedin
  - title: github
    url: https://github.com/KaloyanTodorov
    icon: fab fa-github
  - title: facebook
    url: https://facebook.com/kpetev
    icon: fab fa-facebook
  - title: instagram
    url: https://instagram.com/kizzata/
    icon: fab fa-instagram
  - title: twitter
    url: https://twitter.com/kicata
    icon: fab fa-twitter
    
workplaces:
  - from: September 2018 
    to: December 2018
    company: Holler.live
    position: Javascript Intern
    description: Participate in Front-end development
    notes: Techonologies used include ReactJS, git, Jira, Scrum
  - from: September 2010
    to: September 2018
    company: Fly Research
    position: Survey Scripter
    description: Designing, creating, testing, launching, managing fieldwork, data checking online marketing reseearch surveys for various clients.
    notes: CMS's used include Questback, Nebu, Kinesis Panel & Survey, Sawtooth (SSI Web)
  - from: January 2010
    to: September 2010
    company: Map Marketing
    position: Survey scripter
    description: Creating, testing online marketing research surveys
    notes: CMS used Confirmit
  - from: July 2007
    to: January 2010
    company: Map Marketing
    position: Sample only mananger
    description: Launch and manage fieldwork for Sample only team USA
    notes: CMS's used Net-MR, Marsc

education:
  - timespan: 2019 - Present
    school: SoftUni
    degree: JavaScript Developer
    technologies: VanillaJS, jQuery, Ajax, Async and Promises, SammyJS, Handlebars, Mocha, Bootstrap, CSS, Sass, Jekyll.
    notes-edu: Refreshing JavaScript and Front-end knowledge.
  - timespan: 2015 - 2016
    school: SoftUni
    degree: Software Development
    technologies: JavaScript, PHP, Java, C#
    notes-edu: First steps in programming. Had to drop it because of personal reasons.
  - tiemspan: 2010 - 2012
    school: Sofia University
    degree: MA, Distributed Systems and Mobile technologies
    technologies: MS Servers configuration, Cisco routers, switches, AP configuration, System administration.
    notes-edu: Did not finish
  - timespan: 2006 - 2010
    school: UNWE (UNSS)
    degree: BA, Sociology and Social sciences
  - timespan: 2000 - 2006
    school: PMG N. Obreshkov Kazanlak
    technologies: Maths, English, Biology, Chemistry
